# Generated by Django 4.1 on 2022-09-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0002_profile_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
